---
categories:
  - title: "🚨 Breaking Changes"
    labels:
      - "breaking-change"

  - title: "🚀 Features"
    labels:
      - "type: feature"

  - title: "🐛 Bug Fixes"
    labels:
      - "type: bugfix"

  - title: "🏎️ Tuning"
    labels:
      - "type: performance"
      - "type: style"

  - title: "🛠️ Tooling"
    labels:
      - "type: build"
      - "type: ci"

  - title: "🧰 Maintenance"
    labels:
      - "type: chore"
      - "type: docs"
      - "type: refactor"
      - "type: reversion"
      - "type: test"

exclude-labels:
  - "release"

change-template: "- $TITLE (#$NUMBER)"

name-template: "$NEXT_PATCH_VERSION"

tag-template: "$NEXT_PATCH_VERSION"

template: |
  $CHANGES
