---
name: Sync Labels

"on":
  push:
    branches:
      - dev
    paths:
      - .github/config/labels.yml
      - .github/config/labeler.yml

  workflow_dispatch:

jobs:
  labels:
    name: ♻️ Sync labels
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4

      - name: 🚀 Run Label Syncer
        uses: micnncim/action-label-syncer@v1.3.0
        with:
          manifest: .github/config/labels.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
